require('dotenv').config();
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcrypt');
const pool = require('../config/db');

// Single source of truth: the same seed-data.json the web client's mock-api.js
// reads. We intentionally do NOT duplicate a second copy of this data — the
// custom backend, the Appwrite backend, and the mock client all seed from
// this one file, so all three "backends" a reviewer switches between in
// index.html show the same three users.
const SEED_PATH = path.join(__dirname, '..', '..', '..', 'web', 'seed-data.json');
const STORAGE_DIR = path.join(__dirname, '..', '..', 'storage');
const SALT_ROUNDS = Number(process.env.BCRYPT_SALT_ROUNDS) || 12;

async function seed() {
  const raw = JSON.parse(fs.readFileSync(SEED_PATH, 'utf8'));
  fs.mkdirSync(STORAGE_DIR, { recursive: true });

  // Wipe existing data so this script is safely re-runnable.
  await pool.query('TRUNCATE files, sessions, login_attempts, users RESTART IDENTITY CASCADE');

  for (const u of raw.users) {
    const passwordHash = await bcrypt.hash(u.password, SALT_ROUNDS);
    const userResult = await pool.query(
      `INSERT INTO users (email, password_hash, full_name, display_name, bio, role, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING id`,
      [
        u.email,
        passwordHash,
        u.profile.fullName,
        u.profile.displayName,
        u.profile.bio,
        u.profile.role,
        u.profile.createdAt,
      ]
    );
    const userId = userResult.rows[0].id;
    console.log(`Seeded user ${u.email} -> ${userId}`);

    for (const f of u.files) {
      // Real placeholder bytes on disk, so /files/:id/download serves an
      // actual file rather than faking a response — same intent as the
      // mock's fake content, but as a genuine file.
      const storageFileName = `${u.id}_${f.id}_${f.fileName}`;
      const content = `This is a seeded placeholder for "${f.fileName}" (${f.mimeType}), owned by ${u.email}.\nGenerated by custom-backend/src/db/seed.js for local testing.\n`;
      fs.writeFileSync(path.join(STORAGE_DIR, storageFileName), content);

      await pool.query(
        `INSERT INTO files (owner_id, file_name, mime_type, size_bytes, storage_path, uploaded_at)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [userId, f.fileName, f.mimeType, Buffer.byteLength(content), storageFileName, f.uploadedAt]
      );
    }
  }

  console.log('Seed complete.');
  await pool.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
