/**
 * seed.js — creates the 3 test users, their profile data, and their files.
 *
 * Reuses the SAME web/seed-data.json the custom backend seeds from, so
 * whichever backend mode you pick in index.html, the three users
 * (alice/bob/carol) and their files are the same.
 *
 * Profile fields (fullName, bio, role) are stored in each Appwrite Account's
 * "prefs" — a small JSON blob Appwrite scopes to the account itself. There's
 * no API for one user to read another user's prefs, so this gives us profile
 * isolation "for free" without a separate database collection + permissions
 * to configure. (displayName is stored as the Appwrite account "name".)
 *
 * Files are uploaded to Storage AND get a matching metadata document in the
 * "files" collection. Both are created with an explicit
 * Permission.read(Role.user(userId)) — that single line, per file, is what
 * actually enforces "only the owner can read this file". Nothing about
 * Appwrite does this automatically; it has to be set at creation time.
 *
 * Run once: npm run seed  (safe to re-run: it skips users that already exist)
 */
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const {
  Client,
  Users,
  Databases,
  Storage,
  Permission,
  Role,
  ID,
  InputFile,
} = require('node-appwrite');

const client = new Client()
  .setEndpoint(process.env.APPWRITE_ENDPOINT)
  .setProject(process.env.APPWRITE_PROJECT_ID)
  .setKey(process.env.APPWRITE_API_KEY);

const users = new Users(client);
const databases = new Databases(client);
const storage = new Storage(client);

const DB_ID = process.env.APPWRITE_DATABASE_ID;
const FILES_COLLECTION_ID = process.env.APPWRITE_FILES_COLLECTION_ID;
const BUCKET_ID = process.env.APPWRITE_BUCKET_ID;

const SEED_PATH = path.join(__dirname, '..', '..', 'web', 'seed-data.json');

async function findExistingUserByEmail(email) {
  const result = await users.list([`equal("email", ["${email}"])`]);
  return result.users[0] || null;
}

async function main() {
  const raw = JSON.parse(fs.readFileSync(SEED_PATH, 'utf8'));

  for (const u of raw.users) {
    let account = await findExistingUserByEmail(u.email);
    if (account) {
      console.log(`User ${u.email} already exists (${account.$id}), skipping creation.`);
    } else {
      // Server-side user creation — Appwrite hashes and stores the password
      // itself; we never see or store a hash ourselves in this flow.
      account = await users.create(ID.unique(), u.email, undefined, u.password, u.profile.displayName);
      await users.updatePrefs(account.$id, {
        fullName: u.profile.fullName,
        bio: u.profile.bio,
        role: u.profile.role,
        createdAt: u.profile.createdAt,
      });
      console.log(`Created user ${u.email} -> ${account.$id}`);
    }

    for (const f of u.files) {
      const content = Buffer.from(
        `This is a seeded placeholder for "${f.fileName}" (${f.mimeType}), owned by ${u.email}.\n` +
          `Generated by appwrite-backend/scripts/seed.js for local testing.\n`
      );

      const ownerOnly = [
        Permission.read(Role.user(account.$id)),
        Permission.delete(Role.user(account.$id)),
      ];

      const storageFile = await storage.createFile(
        BUCKET_ID,
        ID.unique(),
        InputFile.fromBuffer(content, f.fileName),
        ownerOnly
      );

      await databases.createDocument(
        DB_ID,
        FILES_COLLECTION_ID,
        ID.unique(),
        {
          ownerId: account.$id,
          fileName: f.fileName,
          mimeType: f.mimeType,
          sizeBytes: content.byteLength,
          storageFileId: storageFile.$id,
          uploadedAt: f.uploadedAt,
        },
        ownerOnly
      );
    }
    console.log(`  seeded ${u.files.length} file(s) for ${u.email}`);
  }

  console.log('\nSeed complete. Test credentials (see web/index.html quick-fill buttons):');
  for (const u of raw.users) console.log(`  ${u.email} / ${u.password}`);
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
